server:
  port: 8091

spring:
  application:
    name: team-admin-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:teamadmindb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  jackson:
    default-property-inclusion: non_null


client:
  github:
    baseUrl: https://api.github.com/users/
    token: 4b2431c533eb14b749fb9bafe4aeab178ee9a30d

